### ISSUE TITLE
Add support for new versions of graphql-ruby

### ISSUE THREAD

**Issue by GS-Shahid** [Arkweid/graphql-smart_select#3]
Hi @Arkweid Thanks for creating this smart gem. 

I am trying to integrate this with [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) but found that internals of graphqal-ruby gem has been changed and [apply_scope](https://github.com/Arkweid/graphql-smart_select/blob/3d4427364837fa8d3c01c080ce774cfed46fcd5e/lib/graphql/smart_select.rb#L22) method used by this gem is removed from [GraphQL::Schema::Field](https://github.com/rmosolgo/graphql-ruby/blob/558a43fb1ce444d673267d241ea41b612f5b57c5/lib/graphql/schema/field.rb#L538) class 

Can you please add support for newer version of graphql-ruby?

graphql-ruby version 1.11.0
graphql-smart_select version 0.1.3

**Comment by Arkweid** [comment]
Hi, I haven't enough time for support the newer version. I could merge your PR if you'll make fix.

**Comment by bbugh** [comment]
For anyone else looking at this, `apply_scope` was removed in https://github.com/rmosolgo/graphql-ruby/commit/09c0ec7e1c04614148b10dd1a9a8a38310700814

**Comment by bbugh** [comment]
[I posted a short solution](https://github.com/rmosolgo/graphql-ruby/issues/3351#issuecomment-782372504) that should work the same as this for recent GraphQL versions.
